// ── Google Docs + Drive Service ────────────────────────
// Creates real Google Docs from generated inbox items.
// Documents are stored in a dedicated Omni Cal folder in Drive.

import type { GeneratedItem, GeneratedDocument } from "@/lib/schema";
import { getValidAccessToken } from "./token-store";

const DOCS_API = "https://docs.googleapis.com/v1";
const DRIVE_API = "https://www.googleapis.com/drive/v3";

async function docsFetch(
  path: string,
  accessToken: string,
  options: RequestInit = {}
) {
  const res = await fetch(`${DOCS_API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
  if (!res.ok) {
    throw new Error(`Google Docs API error: ${res.status} ${await res.text()}`);
  }
  return res.json();
}

async function driveFetch(
  path: string,
  accessToken: string,
  options: RequestInit = {}
) {
  const res = await fetch(`${DRIVE_API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
  if (!res.ok) {
    throw new Error(`Google Drive API error: ${res.status} ${await res.text()}`);
  }
  return res.json();
}

export async function getOrCreateOmniCalFolder(
  userId: string
): Promise<string> {
  const token = await getValidAccessToken(userId, "google-docs");
  if (!token) throw new Error("Not connected to Google Docs");

  // Search for existing folder
  const searchParams = new URLSearchParams({
    q: "name='Omni Cal' and mimeType='application/vnd.google-apps.folder' and trashed=false",
    fields: "files(id,name)",
  });

  const result = await driveFetch(`/files?${searchParams}`, token);

  if (result.files && result.files.length > 0) {
    return result.files[0].id;
  }

  // Create folder
  const folder = await driveFetch("/files", token, {
    method: "POST",
    body: JSON.stringify({
      name: "Omni Cal",
      mimeType: "application/vnd.google-apps.folder",
    }),
  });

  return folder.id;
}

export async function createDocument(
  userId: string,
  item: GeneratedItem
): Promise<GeneratedDocument> {
  const token = await getValidAccessToken(userId, "google-docs");
  if (!token) throw new Error("Not connected to Google Docs");

  const folderId = await getOrCreateOmniCalFolder(userId);

  // Create the doc in Drive (inside the Omni Cal folder)
  const driveFile = await driveFetch("/files", token, {
    method: "POST",
    body: JSON.stringify({
      name: item.title,
      mimeType: "application/vnd.google-apps.document",
      parents: [folderId],
    }),
  });

  const docId = driveFile.id;

  // Build document content as batch update requests
  const requests = buildDocumentRequests(item);

  if (requests.length > 0) {
    await docsFetch(`/documents/${docId}:batchUpdate`, token, {
      method: "POST",
      body: JSON.stringify({ requests }),
    });
  }

  return {
    id: `doc-${docId}`,
    userId,
    inboxItemId: item.id,
    provider: "google-docs",
    externalId: docId,
    url: `https://docs.google.com/document/d/${docId}/edit`,
    title: item.title,
    createdAt: new Date().toISOString(),
    folderId,
  };
}

function buildDocumentRequests(
  item: GeneratedItem
): Array<Record<string, unknown>> {
  const requests: Array<Record<string, unknown>> = [];
  let index = 1; // Google Docs index starts at 1

  // Title header
  const titleText = `${item.title}\n`;
  requests.push({
    insertText: { location: { index }, text: titleText },
  });
  requests.push({
    updateParagraphStyle: {
      range: { startIndex: index, endIndex: index + titleText.length },
      paragraphStyle: { namedStyleType: "HEADING_1" },
      fields: "namedStyleType",
    },
  });
  index += titleText.length;

  // Summary
  const summaryText = `${item.summary}\n\n`;
  requests.push({
    insertText: { location: { index }, text: summaryText },
  });
  index += summaryText.length;

  // Metadata line
  const metaText = `Generated by Omni Cal · ${item.trigger}\n\n`;
  requests.push({
    insertText: { location: { index }, text: metaText },
  });
  requests.push({
    updateTextStyle: {
      range: { startIndex: index, endIndex: index + metaText.length },
      textStyle: {
        foregroundColor: {
          color: { rgbColor: { red: 0.5, green: 0.5, blue: 0.5 } },
        },
        fontSize: { magnitude: 10, unit: "PT" },
      },
      fields: "foregroundColor,fontSize",
    },
  });
  index += metaText.length;

  // Content sections
  for (const section of item.content.sections) {
    // Section heading
    const headingText = `${section.heading}\n`;
    requests.push({
      insertText: { location: { index }, text: headingText },
    });
    requests.push({
      updateParagraphStyle: {
        range: { startIndex: index, endIndex: index + headingText.length },
        paragraphStyle: { namedStyleType: "HEADING_2" },
        fields: "namedStyleType",
      },
    });
    index += headingText.length;

    // Body text
    if (section.body) {
      const bodyText = `${section.body}\n\n`;
      requests.push({
        insertText: { location: { index }, text: bodyText },
      });
      index += bodyText.length;
    }

    // Bullet items
    if (section.items) {
      for (const bulletItem of section.items) {
        const bulletText = `${bulletItem}\n`;
        requests.push({
          insertText: { location: { index }, text: bulletText },
        });
        requests.push({
          createParagraphBullets: {
            range: {
              startIndex: index,
              endIndex: index + bulletText.length,
            },
            bulletPreset: "BULLET_DISC_CIRCLE_SQUARE",
          },
        });
        index += bulletText.length;
      }
      // Add spacing after bullets
      const spacer = "\n";
      requests.push({
        insertText: { location: { index }, text: spacer },
      });
      index += spacer.length;
    }
  }

  return requests;
}
